pipeline {
    agent any
    environment {
        app_repo    = "https://github.com/malferov/iac.git"
        project_id  = "mimetic-scion-225018"
    }
    stages {
        stage('Build') {
            steps {
                git branch: 'master', url: "${env.app_repo}"
                sh "docker build -t app app/nodejs/."
                sh "docker tag app gcr.io/${env.project_id}/app:$BUILD_NUMBER"
                withCredentials([file(credentialsId: 'SERVICE_ACCOUNT_KEY', variable: 'FILE')]) {
                    sh "docker login -u _json_key --password-stdin https://gcr.io < $FILE"
                }
                sh "docker push gcr.io/${env.project_id}/app:$BUILD_NUMBER"
            }
        }
        stage('Deploy') {
            steps {
                sh "kubectl set image deployment/app app=gcr.io/${env.project_id}/app:$BUILD_NUMBER"
            }
        }
    }
}
